import 'package:flutter/material.dart';

import 'package:coderasta/app/theme.dart';

/// Terms of Service screen for NavixMind.
class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  static const String tosText = '''
TERMS OF SERVICE
Last updated: February 2025

By using NavixMind ("the App"), you agree to these terms. If you do not agree, do not use the App.

1. AS-IS SOFTWARE
THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. THE DEVELOPER MAKES NO GUARANTEES REGARDING UPTIME, RELIABILITY, ACCURACY, OR AVAILABILITY. THIS APPLIES TO BOTH CLOUD-BASED AND ON-DEVICE AI FEATURES.

2. YOUR API KEY & COSTS
You provide your own Anthropic API key for cloud AI features. You are solely responsible for all API usage costs incurred through the App. The developer has no access to your API key and bears no responsibility for charges on your Anthropic account.

3. ON-DEVICE AI MODELS
The App offers optional offline AI models that run entirely on your device. By downloading and using these models, you agree to the following:
- Models are provided by third-party developers (including Alibaba Cloud / Qwen) and are subject to their respective licenses.
- Some models are marked "Research only" and are licensed exclusively for non-commercial research purposes. You must not use research-only models for any commercial activity.
- Downloaded models are stored on your device and may consume significant storage space (up to several gigabytes). You are responsible for managing your device storage.
- The developer makes no guarantees regarding the accuracy, quality, or safety of AI-generated output from on-device models.
- You may delete downloaded models at any time through the App's settings.

4. YOUR CONTENT
You are solely responsible for all content you process, generate, or store using the App, whether through cloud or on-device AI. You must comply with Anthropic's Acceptable Use Policy (for cloud features), applicable model licenses (for offline features), and all applicable laws.

5. AI-GENERATED CONTENT
Content generated by the App (whether via cloud API or on-device models) may be inaccurate, incomplete, or inappropriate. You are solely responsible for reviewing and verifying all AI-generated content before use. The developer is not responsible for any consequences arising from reliance on AI-generated output.

6. DEVICE PERMISSIONS
The App may request access to device resources including storage and network. These are used solely for app functionality, including downloading and running on-device AI models. You may revoke permissions at any time through your device settings.

7. LIMITATION OF LIABILITY
TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE DEVELOPER SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO: DATA LOSS, API COSTS, DEVICE DAMAGE, STORAGE CONSUMPTION, LOSS OF PROFITS, OR ANY OTHER DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE THE APP.

8. MODIFICATIONS & TERMINATION
The developer may modify, suspend, or discontinue the App (including removing or adding AI models) at any time without notice or liability. These terms may be updated at any time; continued use constitutes acceptance.

9. THIRD-PARTY LICENSES
The App incorporates third-party software and AI models, each subject to its own license terms. A summary of third-party licenses is available in the App's settings under "Open-Source Licenses." By using the App, you agree to comply with all applicable third-party license terms.

10. OPEN SOURCE
The App is open-source software. Use of the source code is subject to the applicable open-source license in the repository.

11. GOVERNING LAW
These terms shall be governed by applicable law. Any disputes shall be resolved in the courts of the developer's jurisdiction.

By using NavixMind, you acknowledge that you have read, understood, and agree to these terms.''';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: RastaTheme.background,
      appBar: AppBar(
        backgroundColor: RastaTheme.background,
        title: const Text('Terms of Service'),
        leading: IconButton(
          icon: Text(
            RastaTheme.iconClose,
            style: TextStyle(
              fontSize: 24,
              color: RastaTheme.textPrimary,
            ),
          ),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Text(
          tosText,
          style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                color: RastaTheme.textPrimary,
                height: 1.6,
              ),
        ),
      ),
    );
  }
}
